# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog():
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(487, 558)
    self.title = QtWidgets.QLabel(Dialog)
    self.title.setGeometry(QtCore.QRect(10, 20, 461, 31))
    font = QtGui.QFont()
    font.setFamily("Calibri Light")
    font.setPointSize(15)
    self.title.setFont(font)
    self.title.setAlignment(QtCore.Qt.AlignCenter)
    self.title.setObjectName("title")
    self.seed_number = QtWidgets.QLineEdit(Dialog)
    self.seed_number.setGeometry(QtCore.QRect(220, 150, 221, 20))
    self.seed_number.setObjectName("seed_number")
    self.randomize_level_order = QtWidgets.QCheckBox(Dialog)
    self.randomize_level_order.setGeometry(QtCore.QRect(230, 249, 211, 21))
    self.randomize_level_order.setObjectName("randomize_level_order")
    self.warps_label = QtWidgets.QLabel(Dialog)
    self.warps_label.setGeometry(QtCore.QRect(30, 230, 91, 21))
    self.warps_label.setObjectName("warps_label")
    self.colors__label = QtWidgets.QLabel(Dialog)
    self.colors__label.setGeometry(QtCore.QRect(30, 300, 91, 21))
    self.colors__label.setObjectName("colors__label")
    self.randomize_character_stats = QtWidgets.QCheckBox(Dialog)
    self.randomize_character_stats.setGeometry(QtCore.QRect(230, 309, 211, 21))
    self.randomize_character_stats.setObjectName("randomize_character_stats")
    self.shuffle_character_stats = QtWidgets.QCheckBox(Dialog)
    self.shuffle_character_stats.setGeometry(QtCore.QRect(230, 329, 211, 21))
    self.shuffle_character_stats.setObjectName("shuffle_character_stats")
    self.characters_label = QtWidgets.QLabel(Dialog)
    self.characters_label.setGeometry(QtCore.QRect(220, 289, 91, 21))
    self.characters_label.setObjectName("characters_label")
    self.lives_continues_label = QtWidgets.QLabel(Dialog)
    self.lives_continues_label.setGeometry(QtCore.QRect(30, 370, 91, 21))
    self.lives_continues_label.setObjectName("lives_continues_label")
    self.add_extra_lives = QtWidgets.QCheckBox(Dialog)
    self.add_extra_lives.setGeometry(QtCore.QRect(40, 390, 201, 21))
    self.add_extra_lives.setObjectName("add_extra_lives")
    self.add_extra_continues = QtWidgets.QCheckBox(Dialog)
    self.add_extra_continues.setGeometry(QtCore.QRect(40, 410, 201, 20))
    self.add_extra_continues.setObjectName("add_extra_continues")
    self.character_select_after_death = QtWidgets.QCheckBox(Dialog)
    self.character_select_after_death.setGeometry(QtCore.QRect(230, 349, 211, 21))
    self.character_select_after_death.setObjectName("character_select_after_death")
    self.enemies_label = QtWidgets.QLabel(Dialog)
    self.enemies_label.setGeometry(QtCore.QRect(220, 389, 91, 21))
    self.enemies_label.setObjectName("enemies_label")
    self.shuffle_some_enemies = QtWidgets.QCheckBox(Dialog)
    self.shuffle_some_enemies.setGeometry(QtCore.QRect(230, 409, 211, 21))
    self.shuffle_some_enemies.setObjectName("shuffle_some_enemies")
    self.levels_label = QtWidgets.QLabel(Dialog)
    self.levels_label.setGeometry(QtCore.QRect(220, 230, 91, 20))
    self.levels_label.setObjectName("levels_label")
    self.input_filename = QtWidgets.QLineEdit(Dialog)
    self.input_filename.setGeometry(QtCore.QRect(220, 70, 221, 20))
    self.input_filename.setReadOnly(True)
    self.input_filename.setObjectName("input_filename")
    self.choose_file_button = QtWidgets.QPushButton(Dialog)
    self.choose_file_button.setGeometry(QtCore.QRect(30, 70, 171, 23))
    self.choose_file_button.setObjectName("choose_file_button")
    self.randomize_button = QtWidgets.QPushButton(Dialog)
    self.randomize_button.setGeometry(QtCore.QRect(30, 480, 121, 23))
    self.randomize_button.setObjectName("randomize_button")
    self.allow_backwards_warps = QtWidgets.QCheckBox(Dialog)
    self.allow_backwards_warps.setGeometry(QtCore.QRect(40, 270, 201, 20))
    self.allow_backwards_warps.setObjectName("allow_backwards_warps")
    self.randomize_warp_destinations = QtWidgets.QCheckBox(Dialog)
    self.randomize_warp_destinations.setGeometry(QtCore.QRect(40, 250, 201, 20))
    self.randomize_warp_destinations.setObjectName("randomize_warp_destinations")
    self.randomize_subspace_palettes = QtWidgets.QCheckBox(Dialog)
    self.randomize_subspace_palettes.setGeometry(QtCore.QRect(40, 340, 201, 20))
    self.randomize_subspace_palettes.setObjectName("randomize_subspace_palettes")
    self.randomize_palettes = QtWidgets.QCheckBox(Dialog)
    self.randomize_palettes.setGeometry(QtCore.QRect(40, 320, 201, 20))
    self.randomize_palettes.setObjectName("randomize_palettes")
    self.new_seed_button = QtWidgets.QPushButton(Dialog)
    self.new_seed_button.setGeometry(QtCore.QRect(30, 150, 171, 23))
    self.new_seed_button.setObjectName("new_seed_button")
    self.output_location = QtWidgets.QLineEdit(Dialog)
    self.output_location.setGeometry(QtCore.QRect(220, 110, 221, 20))
    self.output_location.setText("")
    self.output_location.setReadOnly(True)
    self.output_location.setObjectName("output_location")
    self.choose_output_button = QtWidgets.QPushButton(Dialog)
    self.choose_output_button.setGeometry(QtCore.QRect(30, 110, 171, 23))
    self.choose_output_button.setObjectName("choose_output_button")
    self.flag_string = QtWidgets.QLineEdit(Dialog)
    self.flag_string.setGeometry(QtCore.QRect(220, 190, 221, 20))
    self.flag_string.setObjectName("flag_string")
    self.characters_label_2 = QtWidgets.QLabel(Dialog)
    self.characters_label_2.setGeometry(QtCore.QRect(100, 190, 71, 21))
    self.characters_label_2.setObjectName("characters_label_2")

    self.retranslateUi(Dialog)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.title.setText(_translate("Dialog", "Open Source Zelda 1 Randomizer v0.03 alpha"))
    self.randomize_level_order.setText(_translate("Dialog", "Ticky"))
    self.warps_label.setText(_translate("Dialog", "Ignore this"))
    self.colors__label.setText(_translate("Dialog", "Ignore this"))
    self.randomize_character_stats.setText(_translate("Dialog", "Ticky"))
    self.shuffle_character_stats.setText(_translate("Dialog", "Ticky"))
    self.characters_label.setText(_translate("Dialog", "Ignore this"))
    self.lives_continues_label.setText(_translate("Dialog", "Ignore this"))
    self.add_extra_lives.setText(_translate("Dialog", "Ticky"))
    self.add_extra_continues.setText(_translate("Dialog", "Ticky"))
    self.character_select_after_death.setText(_translate("Dialog", "Ticky"))
    self.enemies_label.setText(_translate("Dialog", "Ignore this"))
    self.shuffle_some_enemies.setText(_translate("Dialog", "Ticky"))
    self.levels_label.setText(_translate("Dialog", "Ignore this"))
    self.choose_file_button.setText(_translate("Dialog", "Choose ROM Location"))
    self.randomize_button.setText(_translate("Dialog", "Randomize!"))
    self.allow_backwards_warps.setText(_translate("Dialog", "Ticky"))
    self.randomize_warp_destinations.setText(_translate("Dialog", "Ticky"))
    self.randomize_subspace_palettes.setText(_translate("Dialog", "Ticky"))
    self.randomize_palettes.setText(_translate("Dialog", "Ticky"))
    self.new_seed_button.setText(_translate("Dialog", "New Seed"))
    self.choose_output_button.setText(_translate("Dialog", "Choose Output Location"))
    self.characters_label_2.setText(_translate("Dialog", "Ignore this"))
