from typing import NewType
from enum import IntEnum

LevelNum = int
CaveNum = int
RoomNum = NewType("RoomNum", int)
PositionNum = NewType("PositionNum", int)


class Range():
  VALID_ROOM_NUMBERS = range(0, 0x80)  # 128 rooms (0-indexed)
  VALID_ROOM_TABLE_NUMBERS = range(0, 6)  # Six tables (0-indexed)
  VALID_LEVEL_NUMBERS = range(1, 10)  # Levels 1-9 (1-indexed)
  VALID_LEVEL_AND_CAVE_NUMBERS = range(1, 11)  # L1-9 plus L10 repreenting OW caves (1-indexed)
  VALID_ITEM_NUMBERS = range(0, 0x40)
  VALID_CAVE_NUMBERS = range(0, 0x16)  # Includes 20 actual +2 virtual caves 0-19, 20-21.
  VALID_CAVE_POSITION_NUMBERS = range(1, 4)  # Three possible positions per cave (1-indexed)


class Direction(IntEnum):
  NORTH = -0x10
  SOUTH = 0x10
  STAIRCASE = 0x00
  WEST = -0x1
  EAST = 0x1


class Item(IntEnum):
  BOMBS = 0x00
  WOOD_SWORD = 0x01
  WHITE_SWORD = 0x02
  MAGICAL_SWORD = 0x03
  NO_ITEM = 0x03
  BAIT = 0x04
  RECORDER = 0x05
  BLUE_CANDLE = 0x06
  RED_CANDLE = 0x07
  WOOD_ARROWS = 0x08
  SILVER_ARROWS = 0x09
  BOW = 0x0A
  MAGICAL_KEY = 0x0B
  RAFT = 0x0C
  LADDER = 0x0D
  TRIFORCE_OF_POWER = 0x0E
  FIVE_RUPEES = 0x0F
  WAND = 0x10
  BOOK = 0x11
  BLUE_RING = 0x12
  RED_RING = 0x13
  POWER_BRACELET = 0x14
  LETTER = 0x15
  COMPASS = 0x16
  MAP = 0x17
  RUPEE = 0x18
  KEY = 0x19
  HEART_CONTAINER = 0x1A
  TRIFORCE = 0x1B
  MAGICAL_SHIELD = 0x1C
  WOODEN_BOOMERANG = 0x1D
  MAGICAL_BOOMERANG = 0x1E
  BLUE_POTION = 0x1F
  RED_POTION = 0x20
  SINGLE_HEART = 0x22
  OVERWORLD_NO_ITEM = 0x3F
  BEAST_DEFEATED_VIRTUAL_ITEM = 0x98
  KIDNAPPED_RESCUED_VIRTUAL_ITEM = 0x99

  def IsProgressiveUpgradeItem(self):
    return self in [Item.WOOD_ARROWS, Item.SILVER_ARROWS, Item.BLUE_CANDLE, Item.RED_CANDLE,
       Item.WOOD_SWORD, Item.WHITE_SWORD, Item.MAGICAL_SWORD, Item.BLUE_RING, Item.RED_RING]

  def IsMinorDungeonItem(self):
    return self in [Item.BOMBS, Item.FIVE_RUPEES, Item.KEY, Item.COMPASS, Item.MAP]

  def IsMajorItem(self):
      # Check if the current item is one of the sword items
      return self in [Item.WOOD_SWORD, Item.WHITE_SWORD, Item.MAGICAL_SWORD, Item.RECORDER,
          Item.BLUE_CANDLE, Item.RED_CANDLE, Item.WOOD_ARROWS, Item.SILVER_ARROWS, Item.BOW,
          Item.MAGICAL_KEY, Item.RAFT, Item.LADDER, Item.WAND, Item.BOOK, Item.BLUE_RING, 
          Item.RED_RING, Item.POWER_BRACELET, Item.HEART_CONTAINER, Item.WOODEN_BOOMERANG, 
          Item.MAGICAL_BOOMERANG]

class RoomType(IntEnum):
  PLAIN_ROOM = 0x00
  SPIKE_TRAP_ROOM = 0x01
  FOUR_SHORT_ROOM = 0x02
  FOUR_TALL_ROOM = 0x03
  AQUAMENTUS_ROOM = 0x04
  GLEEOK_ROOM = 0x05
  GOHMA_ROOM = 0x06
  THREE_ROWS = 0x07
  REVERSE_C = 0x08
  CIRCLE_WALL = 0x09
  DOUBLE_BLOCK = 0x0A
  LAVA_MOAT = 0x0B
  MAZE_ROOM = 0x0C
  GRID_ROOM = 0x0D
  VERTICAL_CHUTE_ROOM = 0x0E
  HORIZONTAL_CHUTE_ROOM = 0x0F
  VERTICAL_ROWS = 0x10
  ZIGZAG_ROOM = 0x11
  T_ROOM = 0x12
  VERTICAL_MOAT_ROOM = 0x13
  CIRCLE_MOAT_ROOM = 0x14
  POINTLESS_MOAT_ROOM = 0x15
  CHEVY_ROOM = 0x16
  NSU = 0x17
  HORIZONTAL_MOAT_ROOM = 0x18
  DOUBLE_MOAT_ROOM = 0x19
  DIAMOND_STAIR_ROOM = 0x1A
  NARROW_STAIR_ROOM = 0x1B
  SPIRAL_STAIR_ROOM = 0x1C
  DOUBLE_SIX_BLOCK_ROOM = 0x1D
  SINGLE_SIX_BLOCK_ROOM = 0x1E
  FIVE_PAIR_ROOM = 0x1F
  TURNSTILE_ROOM = 0x20
  ENTRANCE_ROOM = 0x21
  SINGLE_BLOCK_ROOM = 0x22
  TWO_FIREBALL_ROOM = 0x23
  FOUR_FIREBALL_ROOM = 0x24
  DESERT_ROOM = 0x25
  BLACK_ROOM = 0x26
  ZELDA_ROOM = 0x27
  GANNON_ROOM = 0x28
  TRIFORCE_ROOM = 0x29
  TRANSPORT_STAIRCASE = 0x3E
  ITEM_STAIRCASE = 0x3F
  
  def HasOpenStaircase(self):
    return self in [
        RoomType.DIAMOND_STAIR_ROOM,
        RoomType.NARROW_STAIR_ROOM,
        RoomType.SPIRAL_STAIR_ROOM
    ]

  def CanHavePushBlock(self):
    return self in [
        RoomType.SPIKE_TRAP_ROOM,
        RoomType.GOHMA_ROOM,
        RoomType.THREE_ROWS,
        RoomType.REVERSE_C,
        RoomType.CIRCLE_WALL,
        RoomType.DOUBLE_BLOCK,
        RoomType.MAZE_ROOM,
        RoomType.GRID_ROOM,
        RoomType.ZIGZAG_ROOM,
        RoomType.FIVE_PAIR_ROOM,
        RoomType.SINGLE_BLOCK_ROOM,
    ]

class Enemy(IntEnum):
  NOTHING = 0x00
  BLUE_LYNEL = 0x01
  RED_LYNEL =  0x02
  BLUE_MOBLIN = 0x03
  RED_MOBLIN = 0x04
  BLUE_GORIYA = 0x05
  RED_GORIYA = 0x06
  RED_OCTOROK_1 = 0x07
  RED_OCTOROK_2 = 0x08
  BLUE_OCTOROK_1 = 0x09
  BLUE_OCTOROK_2 = 0x0A
  RED_DARKNUT = 0x0B
  BLUE_DARKNUT = 0x0C
  BLUE_TEKTITE = 0x0D
  RED_TEKTITE = 0x0E
  BLUE_LEVER = 0x0F
  RED_LEVER = 0x10
  VIRE = 0x12
  ZOL = 0x13
  GEL_1 = 0x14
  GEL_2 = 0x15
  POLS_VOICE = 0x16
  LIKE_LIKE = 0x17
  BLUE_KEESE = 0x1B
  RED_KEESE = 0x1C
  DARK_KEESE = 0x1D
  RED_WIZZROBE = 0x23
  BLUE_WIZZROBE = 0x24
  WALLMASTER = 0x27
  ROPE = 0x28
  STALFOS = 0x2A
  BUBBLE = 0x2B
  GIBDO = 0x30
  TRIPLE_DODONGO = 0x31
  SINGLE_DODONGO = 0x32
  BLUE_GOHMA = 0x33
  RED_GOHMA = 0x34
  RUPEE_BOSS = 0x35
  HUNGRY_GORIYA = 0x36
  THE_KIDNAPPED = 0x37
  TRIPLE_DIGDOGGER = 0x38
  SINGLE_DIGDOGGER = 0x39
  RED_LANMOLA = 0x3A
  BLUE_LANMOLA = 0x3B
  MANHANDALA = 0x3C
  AQUAMENTUS = 0x3D
  THE_BEAST = 0x3E

  # Start of "mixed" enemy types
  MOLDORM = 0x41
  GLEEOK_1 = 0x42
  GLEEOK_2 = 0x43
  GLEEOK_3 = 0x44
  GLEEOK_4 = 0x45
  PATRA_2 = 0x47
  PATRA_1 = 0x48
  THREE_PAIRS_OF_TRAPS = 0x49
  CORNER_TRAPS = 0x4A
  OLD_MAN = 0x4B
  OLD_MAN_2 = 0x4C
  OLD_MAN_3 = 0x4D
  OLD_MAN_4 = 0x4E
  BOMB_UPGRADER = 0x4F
  OLD_MAN_5 = 0x50
  MUGGER = 0x51
  OLD_MAN_6 = 0x52
  ZOL_TRAPS = 0x6D
  ZOL_KEESE = 0x6F
  KEESE_TRAPS = 0x6E
  POLS_VOICE_GIBDO_KEESE = 0x70
  BLUE_WIZZROBE_RED_WIZZROBE_BUBBLE = 0x71
  VIRE_BUBBLE = 0x72
  LIKE_LIKE_ZOL_BUBBLE = 0x73
  BLUE_DARKNUT_RED_DARKNUT_GORIYA_BUBBLE = 0x74
  BLUE_GORIYA_KEESE_BUBBLE = 0x75
  LIKE_LIKE_TRAPS = 0x76
  BLUE_WIZZROBE_RED_WIZZROBE_TRAPS = 0x77
  BLUE_DARKNUT_RED_DARKNUT_POLS_VOICE = 0x78
  WALLMASTER_BUBBLE = 0x79
  BLUE_GORIYA_RED_GORIYA = 0x7A
  BLUE_WIZZROBE_RED_WIZZROBE = 0x7B
  BLUE_WIZZROBE_LIKE_LIKE_BUBBLE = 0x7C
  #TODO_FIGURE_OUT_WHAT_THIS_IS_3 = 0x08
  #TODO_FIGURE_OUT_WHAT_THIS_IS = 0x18
  #TODO_FIGURE_OUT_WHAT_THIS_IS_2 = 0x29
  
  def IsGleeokOrPatra(self):
    return self in [
      Enemy.GLEEOK_1, Enemy.GLEEOK_2, Enemy.GLEEOK_3, Enemy.GLEEOK_4, Enemy.PATRA_1, Enemy.PATRA_2
    ]


class WallType(IntEnum):
  OPEN_DOOR = 0
  SOLID_WALL = 1
  WALK_THROUGH_WALL_1 = 2
  WALK_THROUGH_WALL_2 = 3
  BOMB_HOLE = 4
  LOCKED_DOOR_1 = 5
  LOCKED_DOOR_2 = 6
  SHUTTER_DOOR = 7


"""class TextSpeed(IntEnum):
  VERY_FAST = 2
  FAST = 4
  NORMAL = 6
  SLOW = 8
  VERY_SLOW = 10"""
